---
- name: config | Configuring {{ elasticsearch['config_dir'] + '/elasticsearch.yml' }}
  ansible.builtin.template:
    src: etc/elasticsearch/elasticsearch.yml.j2
    dest: "{{ elasticsearch['config_dir'] + '/elasticsearch.yml' }}"
    owner: root
    group: elasticsearch
    mode: u=rw,g=r,o=r
  become: true
  notify: restart elasticsearch

- name: config | Configuring /etc/default/elasticsearch
  ansible.builtin.template:
    src: etc/default/elasticsearch.j2
    dest: /etc/default/elasticsearch
    owner: root
    group: root
    mode: u=rw,g=r,o=r
  become: true
  notify: restart elasticsearch
  when: ansible_os_family == "Debian"
