---
- name: debian | Installing Pre-Reqs
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - gnupg
      - software-properties-common
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Copying Elasticsearch GPG Key
  ansible.builtin.copy:
    src: GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch
    mode: u=rw,g=r,o=r

- name: debian | Adding Elasticsearch GPG Key
  ansible.builtin.apt_key:
    file: /tmp/GPG-KEY-elasticsearch
    state: present
  become: true

- name: debian | Adding Elasticsearch Repo
  ansible.builtin.apt_repository:
    repo: "{{ 'deb ' + elasticsearch.repo_url + '/' + elasticsearch.version_major_version + '/apt stable main' }}"
    state: present
  become: true

- name: debian | Enabling deb http://http.debian.net/debian jessie-backports main
  ansible.builtin.apt_repository:
    repo: deb http://http.debian.net/debian jessie-backports main
    state: present
  become: true
  when:
    - ansible_distribution == "Debian"
    - ansible_distribution_release == "jessie"

- name: debian | Adding OpenJDK PPA
  ansible.builtin.apt_repository:
    repo: ppa:openjdk-r/ppa
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Ubuntu"

- name: debian | Installing Java
  ansible.builtin.apt:
    name: "{{ elasticsearch_java_package }}"
    state: present
  become: true
  register: result
  until: result is successful

- name: debian | Installing Elasticsearch {{ elasticsearch['version_minor_version'] }}
  ansible.builtin.apt:
    name: "{{ elasticsearch_package }}"
    state: present
  become: true
  register: result
  until: result is successful
