---
# tasks file for ansible-elasticsearch

- name: Setting facts
  ansible.builtin.include_tasks: set_facts.yml

- name: Debian specific tasks
  ansible.builtin.include_tasks: debian.yml
  when: ansible_os_family == "Debian"

- name: RHEL specific tasks
  ansible.builtin.include_tasks: redhat.yml
  when: ansible_os_family == "RedHat"

- name: Configure Elasticsearch
  ansible.builtin.include_tasks: config.yml
  when: elasticsearch['config']|bool

- name: Manage Elasticsearch service
  ansible.builtin.include_tasks: service.yml
