---
- name: redhat | Copying Elasticsearch GPG Key
  ansible.builtin.copy:
    src: GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch
    mode: u=rw,g=r,o=r

- name: redhat | Adding Elasticsearch GPG Key
  ansible.builtin.rpm_key:
    key: /tmp/GPG-KEY-elasticsearch
    state: present
  become: true

- name: redhat | Adding Elasticsearch Repo
  ansible.builtin.yum_repository:
    baseurl: "{{ elasticsearch.repo_url + '/' + elasticsearch.version_major_version + '/yum' }}"
    description: "Elasticsearch repository for {{ elasticsearch.version_major_version }} packages"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ elasticsearch.repo_key }}"
    name: "{{ 'elasticsearch-' + elasticsearch.version_major_version }}"
    state: present
  become: true

- name: redhat | Installing Java
  ansible.builtin.yum:
    name: java-1.8.0-openjdk-headless
    state: present
  become: true
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Elasticsearch
  ansible.builtin.yum:
    name: "{{ elasticsearch_package }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Java
  ansible.builtin.dnf:
    name: java
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"

- name: redhat | Installing Elasticsearch
  ansible.builtin.dnf:
    name: "{{ elasticsearch_package }}"
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution == "Fedora"
