---
- name: Converge
  hosts: all
  vars:
    elasticsearch:
      # Defines if elasticsearch should be configured
      config: true

      config_dir: /etc/elasticsearch
      data_dir: /var/lib/elasticsearch

      # Defines the amount of memory to allocate
      # Heap Size (defaults to 256m min, 1g max)
      # 50% of max memory is good.
      heap_size: "{{ (ansible_memtotal_mb * elasticsearch_heap_size_multiplier)|round|int }}m"

      home_dir: /usr/share/elasticsearch
      listen_interface: "{{ ansible_default_ipv4.interface }}"
      log_dir: /var/log/elasticsearch
      # max_locked_memory: unlimited
      # max_map_count: 262144
      # max_open_files: 65536
      pid_dir: /var/run/elasticsearch
      repo_key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      repo_url: https://artifacts.elastic.co/packages
      startup_sleep_time: 5
      # Defines Elasticsearch Major release (1.7|2.x|5.x|6.x|7.x)
      version_major_version: oss-7.x
      # Defines Elasticsearch Minor release
      version_minor_version: 7.8.0
  tasks:
    - name: Include ansible-elasticsearch
      ansible.builtin.include_role:
        name: ansible-elasticsearch
